"""empty message

Revision ID: 0c914959f059
Revises: a02b4ae6ef6b
Create Date: 2021-06-05 23:22:13.464129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c914959f059'
down_revision = 'a02b4ae6ef6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('secret_key', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'user_details', ['secret_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_details', type_='unique')
    op.drop_column('user_details', 'secret_key')
    # ### end Alembic commands ###
