"""empty message

Revision ID: 226eed5ee27c
Revises: 9999434d3181
Create Date: 2021-05-22 21:01:56.040008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226eed5ee27c'
down_revision = '9999434d3181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloth_table', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('jewellery_table', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jewellery_table', 'description')
    op.drop_column('cloth_table', 'description')
    # ### end Alembic commands ###
