"""empty message

Revision ID: 40ee7a70dfd2
Revises: 
Create Date: 2021-05-22 16:30:13.863637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ee7a70dfd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_details',
    sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.NullType(), nullable=True),
    sa.Column('card_no', sa.String(length=200), nullable=True),
    sa.Column('card_name', sa.String(length=200), nullable=True),
    sa.Column('cvv', sa.String(length=200), nullable=True),
    sa.Column('expiry_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_name'),
    sa.UniqueConstraint('card_no'),
    sa.UniqueConstraint('cvv')
    )
    op.create_table('cloth_table',
    sa.Column('prod_id', sa.String(length=12), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('img_url', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prod_id')
    )
    op.create_table('jewellery_table',
    sa.Column('prod_id', sa.String(length=12), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('img_url', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prod_id')
    )
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=True),
    sa.Column('fname', sa.String(length=50), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    op.drop_table('jewellery_table')
    op.drop_table('cloth_table')
    op.drop_table('card_details')
    # ### end Alembic commands ###
