"""empty message

Revision ID: 53e3a410ee70
Revises: 8dd9756a075e
Create Date: 2021-06-05 15:56:42.488547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e3a410ee70'
down_revision = '8dd9756a075e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('username', sa.String(length=300), nullable=True))
    op.create_unique_constraint(None, 'user_details', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_details', type_='unique')
    op.drop_column('user_details', 'username')
    # ### end Alembic commands ###
