"""empty message

Revision ID: 57e8664f1d24
Revises: 226eed5ee27c
Create Date: 2021-05-23 14:38:31.853952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57e8664f1d24'
down_revision = '226eed5ee27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_details_card_name_key', 'card_details', type_='unique')
    op.drop_constraint('card_details_card_no_key', 'card_details', type_='unique')
    op.drop_column('card_details', 'card_no')
    op.drop_column('card_details', 'card_name')
    op.add_column('user_details', sa.Column('cart_item', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=True))
    op.drop_constraint('user_details_email_key', 'user_details', type_='unique')
    op.drop_constraint('user_details_password_key', 'user_details', type_='unique')
    op.drop_column('user_details', 'email')
    op.drop_column('user_details', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('user_details', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_details_password_key', 'user_details', ['password'])
    op.create_unique_constraint('user_details_email_key', 'user_details', ['email'])
    op.drop_column('user_details', 'cart_item')
    op.add_column('card_details', sa.Column('card_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('card_details', sa.Column('card_no', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_unique_constraint('card_details_card_no_key', 'card_details', ['card_no'])
    op.create_unique_constraint('card_details_card_name_key', 'card_details', ['card_name'])
    # ### end Alembic commands ###
