"""empty message

Revision ID: 7161c49d4ee2
Revises: 40ee7a70dfd2
Create Date: 2021-05-22 16:44:54.386064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7161c49d4ee2'
down_revision = '40ee7a70dfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_details', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'card_details', 'user_details', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card_details', type_='foreignkey')
    op.drop_column('card_details', 'user_id')
    # ### end Alembic commands ###
