"""empty message

Revision ID: 8dd9756a075e
Revises: 8871826f01a3
Create Date: 2021-06-05 15:56:26.781335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd9756a075e'
down_revision = '8871826f01a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_details_username_key', 'user_details', type_='unique')
    op.drop_column('user_details', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('username', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_details_username_key', 'user_details', ['username'])
    # ### end Alembic commands ###
