"""empty message

Revision ID: b59f484359eb
Revises: 2750a67d58b1
Create Date: 2021-06-05 16:44:42.580798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59f484359eb'
down_revision = '2750a67d58b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('user_name', sa.String(length=300), nullable=True))
    op.create_unique_constraint(None, 'user_details', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_details', type_='unique')
    op.drop_column('user_details', 'user_name')
    # ### end Alembic commands ###
