"""empty message

Revision ID: c994b59dd640
Revises: e9de75bd8540
Create Date: 2021-06-05 23:09:55.340113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c994b59dd640'
down_revision = 'e9de75bd8540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_details_secret_key_key', 'user_details', type_='unique')
    op.drop_column('user_details', 'secret_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('secret_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_details_secret_key_key', 'user_details', ['secret_key'])
    # ### end Alembic commands ###
