"""empty message

Revision ID: e9de75bd8540
Revises: b59f484359eb
Create Date: 2021-06-05 23:04:29.602801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9de75bd8540'
down_revision = 'b59f484359eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('iv', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'iv')
    # ### end Alembic commands ###
